<?php 

class Escolas {

 public $id;
 public $inepEscola;
 public $codigoEscola;
 public $nome;
 public $latitude;
 public $longitude;
 public $cep;
 public $endereco;
 public $enderecoNumero;
 public $enderecoComplemento;
 public $bairroCodigo;
 public $bairro;
 public $telefone;
 public $fax;
 public $email;
 public $orgaoRegional;
 public $regulamentacao;
 public $funcionamentoPredioEscolar;
 public $funcionamentoTemplo;
 public $funcionamentoEmpresa;
 public $funcionamentoOutrasEscolas;
 public $funcionamentoGalpao;
 public $funcionamentoOutros;
 public $formaOcupacao;
 public $aguaRedePublica;
 public $aguaPocoArtesiano;
 public $aguaCacimba;
 public $aguaFonte;
 public $esgotoRedePublica;
 public $esgotoFossa;
 public $esgotoInexistente;
 public $lixoColetaPeriodica;
 public $lixoOutraArea;
 public $dependenciaDiretoria;
 public $dependenciaProfessores;
 public $dependenciaSecretaria;
 public $dependenciaLaboratorioInformatica;
 public $dependenciaLaboratorioCiencias;
 public $dependenciaAee;
 public $dependenciaQuadraCoberta;
 public $dependenciaQuadraDescoberta;
 public $dependenciaCozinha;
 public $dependenciaBiblioteca;
 public $dependenciaLeitura;
 public $dependenciaParqueInfantil;
 public $dependenciaBercario;
 public $dependenciaBanheiroFora;
 public $dependenciaBanheiroDentro;
 public $dependenciaBanheiroInfantil;
 public $dependenciaBanheiroDeficiencia;
 public $dependenciaViasAdequadasDeficiencia;
 public $dependenciaBanheiroChuveiro;
 public $dependenciaRefeitorio;
 public $dependenciaDespensa;
 public $dependenciaAlmoxarifado;
 public $dependenciaAuditorio;
 public $dependenciaPatioCoberto;
 public $dependenciaPatioDescoberto;
 public $dependenciaAlojamentoAluno;
 public $dependenciaAlojamentoProfessor;
 public $dependenciaAreaVerde;
 public $dependenciaLavanderia;
 public $quantidadeSalasExistentes;
 public $quantidadeSalasUtilizadasForaEDentro;
 public $equipamentosTelevisao;
 public $equipamentosVideocassete;
 public $equipamentosDvd;
 public $equipamentosAntenaParabolica;
 public $equipamentosCopiadora;
 public $equipamentosRetroprojetor;
 public $equipamentosImpressora;
 public $equipamentosAparelhoSom;
 public $equipamentosProjetorMultimidia;
 public $equipamentosFax;
 public $equipamentosMaquinaFotografica;
 public $equipamentosComputadores;
 public $computadoresQuantidade;
 public $computadoresQtdAdministrativo;
 public $computadoresQtdAlunos;
 public $acessoInternet;
 public $bandaLarga;
 public $totalFuncionarios;
 public $brasilAlfabetizado;
 public $abreFinaisSemana;
 public $modalidadeRegular;
 public $modalidadeEspecial;
 public $modalidadeEja;
 public $regularCreche;
 public $regularPreescolar;
 public $regularFundamental9;
 public $especialFundamental9;
 public $especialEjaFundamental;
 public $ejaFundamental;
 public $ejaProjovem;

 public function __construct($id,$inepEscola,$codigoEscola,$nome,$latitude,$longitude,$cep,$endereco,$enderecoNumero,$enderecoComplemento,$bairroCodigo,$bairro,$telefone,$fax,$email,$orgaoRegional,$regulamentacao,$funcionamentoPredioEscolar,$funcionamentoTemplo,$funcionamentoEmpresa,$funcionamentoOutrasEscolas,$funcionamentoGalpao,$funcionamentoOutros,$formaOcupacao,$aguaRedePublica,$aguaPocoArtesiano,$aguaCacimba,$aguaFonte,$esgotoRedePublica,$esgotoFossa,$esgotoInexistente,$lixoColetaPeriodica,$lixoOutraArea,$dependenciaDiretoria,$dependenciaProfessores,$dependenciaSecretaria,$dependenciaLaboratorioInformatica,$dependenciaLaboratorioCiencias,$dependenciaAee,$dependenciaQuadraCoberta,$dependenciaQuadraDescoberta,$dependenciaCozinha,$dependenciaBiblioteca,$dependenciaLeitura,$dependenciaParqueInfantil,$dependenciaBercario,$dependenciaBanheiroFora,$dependenciaBanheiroDentro,$dependenciaBanheiroInfantil,$dependenciaBanheiroDeficiencia,$dependenciaViasAdequadasDeficiencia,$dependenciaBanheiroChuveiro,$dependenciaRefeitorio,$dependenciaDespensa,$dependenciaAlmoxarifado,$dependenciaAuditorio,$dependenciaPatioCoberto,$dependenciaPatioDescoberto,$dependenciaAlojamentoAluno,$dependenciaAlojamentoProfessor,$dependenciaAreaVerde,$dependenciaLavanderia,$quantidadeSalasExistentes,$quantidadeSalasUtilizadasForaEDentro,$equipamentosTelevisao,$equipamentosVideocassete,$equipamentosDvd,$equipamentosAntenaParabolica,$equipamentosCopiadora,$equipamentosRetroprojetor,$equipamentosImpressora,$equipamentosAparelhoSom,$equipamentosProjetorMultimidia,$equipamentosFax,$equipamentosMaquinaFotografica,$equipamentosComputadores,$computadoresQuantidade,$computadoresQtdAdministrativo,$computadoresQtdAlunos,$acessoInternet,$bandaLarga,$totalFuncionarios,$brasilAlfabetizado,$abreFinaisSemana,$modalidadeRegular,$modalidadeEspecial,$modalidadeEja,$regularCreche,$regularPreescolar,$regularFundamental9,$especialFundamental9,$especialEjaFundamental,$ejaFundamental,$ejaProjovem) {
        
	$this->id = $id;
	$this->inepEscola = $inepEscola;
	$this->codigoEscola = $codigoEscola;
	$this->nome = $nome;
	$this->latitude = $latitude;
	$this->longitude = $longitude;
	$this->cep = $cep;
	$this->endereco = $endereco;
	$this->enderecoNumero = $enderecoNumero;
	$this->enderecoComplemento = $enderecoComplemento;
	$this->bairroCodigo = $bairroCodigo;
	$this->bairro = $bairro;
	$this->telefone = $telefone;
	$this->fax = $fax;
	$this->email = $email;
	$this->orgaoRegional = $orgaoRegional;
	$this->regulamentacao = $regulamentacao;
	$this->funcionamentoPredioEscolar = $funcionamentoPredioEscolar;
	$this->funcionamentoTemplo = $funcionamentoTemplo;
	$this->funcionamentoEmpresa = $funcionamentoEmpresa;
	$this->funcionamentoOutrasEscolas = $funcionamentoOutrasEscolas;
	$this->funcionamentoGalpao = $funcionamentoGalpao;
	$this->funcionamentoOutros = $funcionamentoOutros;
	$this->formaOcupacao = $formaOcupacao;
	$this->aguaRedePublica = $aguaRedePublica;
	$this->aguaPocoArtesiano = $aguaPocoArtesiano;
	$this->aguaCacimba = $aguaCacimba;
	$this->aguaFonte = $aguaFonte;
	$this->esgotoRedePublica = $esgotoRedePublica;
	$this->esgotoFossa = $esgotoFossa;
	$this->esgotoInexistente = $esgotoInexistente;
	$this->lixoColetaPeriodica = $lixoColetaPeriodica;
	$this->lixoOutraArea = $lixoOutraArea;
	$this->dependenciaDiretoria = $dependenciaDiretoria;
	$this->dependenciaProfessores = $dependenciaProfessores;
	$this->dependenciaSecretaria = $dependenciaSecretaria;
	$this->dependenciaLaboratorioInformatica = $dependenciaLaboratorioInformatica;
	$this->dependenciaLaboratorioCiencias = $dependenciaLaboratorioCiencias;
	$this->dependenciaAee = $dependenciaAee;
	$this->dependenciaQuadraCoberta = $dependenciaQuadraCoberta;
	$this->dependenciaQuadraDescoberta = $dependenciaQuadraDescoberta;
	$this->dependenciaCozinha = $dependenciaCozinha;
	$this->dependenciaBiblioteca = $dependenciaBiblioteca;
	$this->dependenciaLeitura = $dependenciaLeitura;
	$this->dependenciaParqueInfantil = $dependenciaParqueInfantil;
	$this->dependenciaBercario = $dependenciaBercario;
	$this->dependenciaBanheiroFora = $dependenciaBanheiroFora;
	$this->dependenciaBanheiroDentro = $dependenciaBanheiroDentro;
	$this->dependenciaBanheiroInfantil = $dependenciaBanheiroInfantil;
	$this->dependenciaBanheiroDeficiencia = $dependenciaBanheiroDeficiencia;
	$this->dependenciaViasAdequadasDeficiencia = $dependenciaViasAdequadasDeficiencia;
	$this->dependenciaBanheiroChuveiro = $dependenciaBanheiroChuveiro;
	$this->dependenciaRefeitorio = $dependenciaRefeitorio;
	$this->dependenciaDespensa = $dependenciaDespensa;
	$this->dependenciaAlmoxarifado = $dependenciaAlmoxarifado;
	$this->dependenciaAuditorio = $dependenciaAuditorio;
	$this->dependenciaPatioCoberto = $dependenciaPatioCoberto;
	$this->dependenciaPatioDescoberto = $dependenciaPatioDescoberto;
	$this->dependenciaAlojamentoAluno = $dependenciaAlojamentoAluno;
	$this->dependenciaAlojamentoProfessor = $dependenciaAlojamentoProfessor;
	$this->dependenciaAreaVerde = $dependenciaAreaVerde;
	$this->dependenciaLavanderia = $dependenciaLavanderia;
	$this->quantidadeSalasExistentes = $quantidadeSalasExistentes;
	$this->quantidadeSalasUtilizadasForaEDentro = $quantidadeSalasUtilizadasForaEDentro;
	$this->equipamentosTelevisao = $equipamentosTelevisao;
	$this->equipamentosVideocassete = $equipamentosVideocassete;
	$this->equipamentosDvd = $equipamentosDvd;
	$this->equipamentosAntenaParabolica = $equipamentosAntenaParabolica;
	$this->equipamentosCopiadora = $equipamentosCopiadora;
	$this->equipamentosRetroprojetor = $equipamentosRetroprojetor;
	$this->equipamentosImpressora = $equipamentosImpressora;
	$this->equipamentosAparelhoSom = $equipamentosAparelhoSom;
	$this->equipamentosProjetorMultimidia = $equipamentosProjetorMultimidia;
	$this->equipamentosFax = $equipamentosFax;
	$this->equipamentosMaquinaFotografica = $equipamentosMaquinaFotografica;
	$this->equipamentosComputadores = $equipamentosComputadores;
	$this->computadoresQuantidade = $computadoresQuantidade;
	$this->computadoresQtdAdministrativo = $computadoresQtdAdministrativo;
	$this->computadoresQtdAlunos = $computadoresQtdAlunos;
	$this->acessoInternet = $acessoInternet;
	$this->bandaLarga = $bandaLarga;
	$this->totalFuncionarios = $totalFuncionarios;
	$this->brasilAlfabetizado = $brasilAlfabetizado;
	$this->abreFinaisSemana = $abreFinaisSemana;
	$this->modalidadeRegular = $modalidadeRegular;
	$this->modalidadeEspecial = $modalidadeEspecial;
	$this->modalidadeEja = $modalidadeEja;
	$this->regularCreche = $regularCreche;
	$this->regularPreescolar = $regularPreescolar;
	$this->regularFundamental9 = $regularFundamental9;
	$this->especialFundamental9 = $especialFundamental9;
	$this->especialEjaFundamental = $especialEjaFundamental;
	$this->ejaFundamental = $ejaFundamental;
	$this->ejaProjovem = $ejaProjovem;

	}

}

?>